CREATE TABLE EXPENSE (
  Expense_ID INT NOT NULL,
  Expense VARCHAR(45) NULL,
  PRIMARY KEY (Expense_ID)
);
 
CREATE TABLE TRIP (
  Trip_ID INT NOT NULL,
  Trip_Name VARCHAR(45) NULL,
  Start_Date VARCHAR(45) NULL,
  End_Date VARCHAR(45) NULL,
  Destination VARCHAR(45) NULL, 
  PRIMARY KEY (Trip_ID)
);
 
ALTER TABLE TRIP ADD Expense_ID INT NOT NULL;
	
ALTER TABLE TRIP ADD FOREIGN KEY (Expense_ID)
	REFERENCES EXPENSE (Expense_ID); 
 
CREATE TABLE TRANSPORTATION (
  Transportation_ID INT NOT NULL,
  Transportation_Type VARCHAR(45) NULL,
  Departure_Location VARCHAR(45) NULL,
  Arrival_Location VARCHAR(45) NULL,
  Departure_Date VARCHAR(45) NULL,
  Return_Date VARCHAR(45) NULL,
  Cost VARCHAR(45) NULL, 
  PRIMARY KEY (Transportation_ID)
);
 
ALTER TABLE TRANSPORTATION ADD Trip_ID INT NOT NULL;
	
ALTER TABLE TRANSPORTATION ADD FOREIGN KEY (Trip_ID)
	REFERENCES TRIP (Trip_ID);	
 
CREATE TABLE ACCOMMODATION (
  Accommodation_ID INT NOT NULL,
  Accommodation_Name VARCHAR(45) NULL,
  Accommodation_Type VARCHAR(45) NULL,
  Street_Address VARCHAR(45) NULL,
  City VARCHAR(45) NULL,
  State VARCHAR(45) NULL,
  Zip_Code VARCHAR(45) NULL,
  Phone_Number VARCHAR(45) NULL, 
  PRIMARY KEY (Accommodation_ID)
);
 
ALTER TABLE ACCOMMODATION ADD Trip_ID INT NOT NULL;
	
ALTER TABLE ACCOMMODATION ADD FOREIGN KEY (Trip_ID)
	REFERENCES TRIP (Trip_ID);

SHOW TABLES;
